### ISSUE TITLE
会有相关视频放出吗?

### ISSUE THREAD

**Issue by baiy** [devlinkcn/ppts_for_php2017#13]
rt

**Comment by chenyangguang** [comment]
会有吗？

**Comment by iYting** [comment]
希望devlink 能把视频发出来吧。。。。。。虽然有点不可能。。

**Comment by myluoluo** [comment]
同样在等视频，不知道会不会有

**Comment by zhufengme** [comment]
视频已经授权 IT大咖说 来制作，只要讲师授权发布，大家就能看到

**Comment by baiy** [comment]
http://www.itdks.com/dakashuo/new/dakalive
上面已经有相关的视频了

**Comment by chenyangguang** [comment]
干得漂亮

**Comment by nadirvishun** [comment]
上方链接已经404了，新的[http://www.itdks.com/eventlist/detail/906](http://www.itdks.com/eventlist/detail/906)，不过是要收费的，128元。
